import type { SettingsTab } from "@/types/dashboard";

export const routes = {
  home: "/",
  login: "/login",
  loginCallback: "/login/callback",
  register: "/register",
  dashboard: "/dashboard",
  waitlists: "/dashboard/waitlists",
  waitlist: (id: string) => `/dashboard/waitlists/${id}`,
  waitlistEdit: (id: string) => `/dashboard/waitlists/${id}/edit`,
  waitlistShare: (id: string) => `/dashboard/waitlists/${id}/share`,
  waitlistRewards: (id: string) => `/dashboard/waitlists/${id}/rewards`,
  waitlistGrowth: (id: string) => `/dashboard/waitlists/${id}/growth`,
  waitlistStreaks: (id: string) => `/dashboard/waitlists/${id}/streaks`,
  waitlistOpenGates: (id: string) => `/dashboard/waitlists/${id}/open-gates`,
  waitlistAnalyticsSources: (id: string) => `/dashboard/waitlists/${id}/analytics/sources`,
  waitlistAnalyticsAudience: (id: string) => `/dashboard/waitlists/${id}/analytics/audience`,
  waitlistAnalyticsFunnel: (id: string) => `/dashboard/waitlists/${id}/analytics/funnel`,
  settings: "/dashboard/settings",
  settingsTab: (tab: SettingsTab) => `/dashboard/settings?tab=${tab}`,
  billing: "/dashboard/billing",
  pricing: "/pricing",
  paymentSuccess: "/payment/success",
  paymentFailed: "/payment/failed",
  paymentPending: "/payment/pending",
  profile: "/dashboard/profile",
  security: "/dashboard/security",
  sessions: "/dashboard/sessions",
  twoFactorSetup: "/two-factor/setup",
  twoFactorDisable: "/two-factor/disable",
  twoFactorVerify: "/two-factor/verify",
  verifyEmail: "/verify-email",
  resendVerification: "/resend-verification",
  create: "/create",
  waitlistPublic: (slug: string) => `/w/${slug}`,
  waitlistTeams: (id: string) => `/dashboard/waitlists/${id}/teams`,
  referral: (code: string) => `/r/${encodeURIComponent(code)}`,
  referralOg: (code: string) => `/og/referral/${encodeURIComponent(code)}`,
} as const;
