"use client";

import * as React from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Activity, Globe, MapPin, MousePointer2, Send, Share2, Smartphone, Target, TrendingUp, Users } from "lucide-react";
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip } from "recharts";
import { EmptyState } from "@/components/ui/empty-state";
import { AnalyticsWaitlistFilter } from "./AnalyticsWaitlistFilter";
import { GeoMap } from "./GeoMap";
import { DeviceChart } from "./DeviceChart";
import { BrowserChart } from "./BrowserChart";
import { FunnelVisualization } from "./FunnelVisualization";
import { GrowthVelocityChart } from "./GrowthVelocityChart";
import { CountryTable } from "./CountryTable";
import { getWorkspaceAudienceAnalytics, getWorkspaceConversionFunnel, getWorkspaceGrowthVelocity, getWorkspaceSourceAnalytics } from "@/services/analytics";
import { useSearchParams } from "next/navigation";

type Feature = "source" | "geo" | "funnel" | "growth";
const heading: Record<Feature, string> = { source: "Source Attribution", geo: "Geo & Device", funnel: "Conversion Funnel", growth: "Growth Velocity" };

export function AnalyticsWorkspaceFeature({ feature }: { feature: Feature }) {
  const waitlistId = useSearchParams().get("waitlistId") ?? undefined;
  const [data, setData] = React.useState<any>(null);
  const [loadedFeature, setLoadedFeature] = React.useState<Feature | null>(null);
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState(false);
  const [mode, setMode] = React.useState<"hourly" | "daily">("daily");

  React.useEffect(() => {
    setLoading(true); setError(false); setData(null);
    const request = feature === "source" ? getWorkspaceSourceAnalytics(waitlistId) : feature === "geo" ? getWorkspaceAudienceAnalytics(waitlistId) : feature === "funnel" ? getWorkspaceConversionFunnel(waitlistId) : getWorkspaceGrowthVelocity(waitlistId);
    request.then((result) => { setData(result); setLoadedFeature(feature); }).catch(() => setError(true)).finally(() => setLoading(false));
  }, [feature, waitlistId]);

  return <section className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-xl font-semibold">{heading[feature]}</h2><p className="text-sm text-muted-foreground">{waitlistId ? "Insights for the selected waitlist." : "Aggregated insights across all your waitlists."}</p></div><AnalyticsWaitlistFilter /></div>{loading || !data || loadedFeature !== feature ? <div className="h-80 animate-pulse rounded-xl bg-surface-muted" aria-label="Loading analytics" /> : error ? <EmptyState title="Unable to load analytics" description="Please try again." /> : feature === "source" ? <Source data={data} /> : feature === "geo" ? <Geo data={data} /> : feature === "funnel" ? <Funnel data={data} /> : <Growth data={data} mode={mode} setMode={setMode} />}</section>;
}

function Metric({ icon: Icon, label, value, note }: any) { return <Card><CardContent className="p-6"><div className="flex items-center gap-2 text-muted-foreground"><Icon className="h-4 w-4"/><span className="text-sm font-medium">{label}</span></div><div className="mt-4 text-3xl font-bold">{value}</div>{note && <p className="mt-1 text-xs text-muted-foreground">{note}</p>}</CardContent></Card>; }
function Source({ data }: { data: any }) { const rows=data.sources.filter((s:any)=>s.signups>0); const colors=["#3b82f6","#10b981","#f59e0b","#8b5cf6","#ec4899"]; return <><div className="grid gap-4 md:grid-cols-4"><Metric icon={Users} label="Visitors" value={data.totalVisitors.toLocaleString()}/><Metric icon={Target} label="Signups" value={data.totalSignups.toLocaleString()}/><Metric icon={Activity} label="Conversion Rate" value={`${data.overallConversionRate}%`}/><Metric icon={TrendingUp} label="Top Source" value={data.sources[0]?.source ?? "—"}/></div><div className="grid gap-6 md:grid-cols-3"><Card><CardHeader><CardTitle>Signup Sources</CardTitle></CardHeader><CardContent><div className="h-64"><ResponsiveContainer><PieChart><Pie data={rows} dataKey="signups" nameKey="source" innerRadius={55} outerRadius={80}>{rows.map((_:any,i:number)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div></CardContent></Card><Card className="md:col-span-2"><CardHeader><CardTitle>Source Performance</CardTitle></CardHeader><CardContent><div className="space-y-2">{data.sources.map((s:any)=><div className="flex justify-between border-b border-border pb-2 text-sm" key={s.source}><span className="font-medium">{s.source}</span><span>{s.visitors} visitors · {s.signups} signups · {s.conversionRate}%</span></div>)}</div></CardContent></Card></div></>; }
function Geo({ data }: { data: any }) { const country=data.countries.find((c:any)=>c.code!=="Unknown"); return <><div className="grid gap-4 md:grid-cols-4"><Metric icon={Users} label="Total Signups" value={data.totalSignups.toLocaleString()} note={`${data.geoAnalyzedSignups} analyzed for location`}/><Metric icon={MapPin} label="Top Country" value={country?.name ?? "Unknown"}/><Metric icon={Smartphone} label="Top Device" value={data.devices.find((d:any)=>d.type!=="UNKNOWN")?.label ?? "Unknown"}/><Metric icon={Globe} label="Top Browser" value={data.browsers.find((b:any)=>b.name!=="Unknown")?.name ?? "Unknown"}/></div><div className="grid gap-6 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader><CardTitle>Signups by Country</CardTitle></CardHeader><CardContent className="space-y-6"><GeoMap data={data.countries}/><CountryTable data={data.countries}/></CardContent></Card><div className="space-y-6"><Card><CardHeader><CardTitle>Devices</CardTitle></CardHeader><CardContent><DeviceChart data={data.devices}/></CardContent></Card><Card><CardHeader><CardTitle>Browsers</CardTitle></CardHeader><CardContent><BrowserChart data={data.browsers}/></CardContent></Card></div></div></>; }
function Funnel({ data }: { data: any }) { return <><div className="grid gap-4 md:grid-cols-4"><Metric icon={Users} label="Page Visits" value={data.pageVisits.toLocaleString()}/><Metric icon={MousePointer2} label="Form Focus" value={data.formFocus.toLocaleString()}/><Metric icon={Send} label="Signups" value={data.signupSubmitted.toLocaleString()}/><Metric icon={Share2} label="Referrals Shared" value={data.referralShared.toLocaleString()}/></div><Card><CardHeader><CardTitle>Conversion Funnel</CardTitle><CardDescription>Visual representation of the user journey.</CardDescription></CardHeader><CardContent><FunnelVisualization steps={data.steps}/></CardContent></Card><div className="grid gap-6 md:grid-cols-2"><Metric icon={TrendingUp} label="Overall Signup Conversion" value={`${data.overallSignupConversion ?? 0}%`} note={`${data.signupSubmitted} of ${data.pageVisits} visitors`}/><Metric icon={Share2} label="Referral Share Rate" value={`${data.referralShareRate ?? 0}%`} note={`${data.referralShared} of ${data.signupSubmitted} signups`}/></div></>; }
function Growth({ data, mode, setMode }: { data: any; mode: "hourly" | "daily"; setMode: (value: "hourly" | "daily") => void }) { const peak=data.summary.peakHour; return <><div className="grid gap-4 md:grid-cols-3"><Metric icon={Users} label="Total Signups" value={data.summary.totalSignups.toLocaleString()}/><Metric icon={TrendingUp} label="Peak Hour" value={peak?.signupCount?.toLocaleString() ?? "—"} note={peak ? new Date(peak.timestamp).toLocaleString() : "No data available"}/><Metric icon={Activity} label="Referral Spikes" value={data.summary.spikeCount}/></div><Card><CardHeader><div className="flex items-center justify-between gap-3"><div><CardTitle>Signup Growth</CardTitle><CardDescription>{mode === "hourly" ? "Signups per hour" : "Signups per day"} with referral spikes marked.</CardDescription></div><select aria-label="Growth interval" value={mode} onChange={(event) => setMode(event.target.value as "hourly" | "daily")} className="rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="hourly">Hourly</option><option value="daily">Daily</option></select></div></CardHeader><CardContent><GrowthVelocityChart data={data[mode]} spikes={data.spikes} viewMode={mode}/></CardContent></Card>{data.spikes.length>0&&<Card><CardHeader><CardTitle>Referral Spike Details</CardTitle></CardHeader><CardContent className="space-y-3">{data.spikes.map((s:any)=><div className="rounded-md border border-border p-3 text-sm" key={s.id}><b>{s.signupCount} signups</b> · {new Date(s.startAt).toLocaleString()} – {new Date(s.endAt).toLocaleString()}</div>)}</CardContent></Card>}</>; }
