"use client";

import * as React from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, Copy, Eye, EyeOff, GripVertical, Plus, Redo2, RotateCcw, Trash2, Undo2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { getPageBuilder, publishPageBuilder, savePageBuilder } from "@/services/dashboard";
import { defaultSection, PAGE_SECTION_TYPES, sectionLabel, singletonSections, type PageConfig, type PageSection, type PageSectionType } from "@/types/page-builder";
import { routes } from "@/lib/routes";
import { uploadFile } from "@/services/files";

type SaveState = "loading" | "saved" | "saving" | "failed" | "publishing" | "published";
const normalize = (sections: PageSection[]) => sections.map((section, order) => ({ ...section, order }));

export default function PageBuilderPage() {
  const params = useParams();
  const waitlistId = params?.id as string;
  const [config, setConfig] = React.useState<PageConfig | null>(null);
  const [version, setVersion] = React.useState(1);
  const [selectedId, setSelectedId] = React.useState<string | null>(null);
  const [state, setState] = React.useState<SaveState>("loading");
  const [history, setHistory] = React.useState<PageConfig[]>([]);
  const [future, setFuture] = React.useState<PageConfig[]>([]);
  const pending = React.useRef<PageConfig | null>(null);
  const saveTimer = React.useRef<ReturnType<typeof setTimeout> | null>(null);

  React.useEffect(() => { if (waitlistId) getPageBuilder(waitlistId).then((data) => { setConfig(data.draftConfig); setVersion(data.version); setSelectedId(data.draftConfig.sections[0]?.id ?? null); setState("saved"); }).catch(() => setState("failed")); }, [waitlistId]);
  const save = React.useCallback(async () => {
    if (!pending.current) return;
    const next = pending.current; pending.current = null; setState("saving");
    try { const result = await savePageBuilder(waitlistId, next, version); setVersion(result.version); setState("saved"); }
    catch { pending.current = next; setState("failed"); }
  }, [version, waitlistId]);
  const update = (next: PageConfig, record = true) => { if (record && config) { setHistory((items) => [...items.slice(-39), config]); setFuture([]); } setConfig(next); pending.current = next; setState("saving"); if (saveTimer.current) clearTimeout(saveTimer.current); saveTimer.current = setTimeout(() => void save(), 1800); };
  React.useEffect(() => () => { if (saveTimer.current) clearTimeout(saveTimer.current); }, []);
  const sections = config?.sections ?? []; const selected = sections.find((section) => section.id === selectedId);
  const changeContent = (key: string, value: string) => selected && update({ ...config!, sections: config!.sections.map((section) => section.id === selected.id ? { ...section, content: { ...section.content, [key]: value } } : section) });
  const move = (id: string, delta: number) => { const index = sections.findIndex((section) => section.id === id); const destination = index + delta; if (destination < 0 || destination >= sections.length) return; const next = [...sections]; [next[index], next[destination]] = [next[destination], next[index]]; update({ ...config!, sections: normalize(next) }); };
  const reorder = (fromId: string, toId: string) => { if (fromId === toId) return; const from = sections.findIndex((section) => section.id === fromId); const to = sections.findIndex((section) => section.id === toId); if (from < 0 || to < 0) return; const next = [...sections]; const [item] = next.splice(from, 1); next.splice(to, 0, item); update({ ...config!, sections: normalize(next) }); };
  const add = (type: PageSectionType) => { if (singletonSections.includes(type) && sections.some((section) => section.type === type)) return; const section = { ...defaultSection(type), order: sections.length }; update({ ...config!, sections: [...sections, section] }); setSelectedId(section.id); };
  const duplicate = (section: PageSection) => { if (singletonSections.includes(section.type)) return; const copy = { ...section, id: `${section.type.toLowerCase()}-${crypto.randomUUID().slice(0, 8)}`, order: sections.length }; update({ ...config!, sections: [...sections, copy] }); setSelectedId(copy.id); };
  const resetSelected = () => { if (!selected) return; const reset = { ...defaultSection(selected.type), id: selected.id, order: selected.order }; update({ ...config!, sections: sections.map((section) => section.id === selected.id ? reset : section) }); };
  const undo = () => { const previous = history.at(-1); if (!previous || !config) return; setHistory((items) => items.slice(0, -1)); setFuture((items) => [config, ...items]); update(previous, false); };
  const redo = () => { const next = future[0]; if (!next || !config) return; setFuture((items) => items.slice(1)); setHistory((items) => [...items, config]); update(next, false); };
  const publish = async () => { if (!config) return; if (pending.current) await save(); setState("publishing"); try { await publishPageBuilder(waitlistId, version); setState("published"); } catch { setState("failed"); } };
  if (!config) return <div className="py-16 text-center text-sm text-muted-foreground">{state === "failed" ? "Unable to load the page builder." : "Loading builder…"}</div>;

  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><Link href={routes.waitlist(waitlistId)} className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" />Back to waitlist</Link><h1 className="mt-2 text-2xl font-semibold">Visual Page Builder</h1></div><div className="flex items-center gap-2"><Button size="sm" variant="ghost" onClick={undo} disabled={!history.length} aria-label="Undo"><Undo2 className="h-4 w-4"/></Button><Button size="sm" variant="ghost" onClick={redo} disabled={!future.length} aria-label="Redo"><Redo2 className="h-4 w-4"/></Button><span className="text-sm text-muted-foreground">{state === "saving" ? "Saving…" : state === "saved" ? "Saved" : state === "published" ? "Published successfully" : state === "failed" ? "Save failed" : state}</span><Button variant="secondary" onClick={() => void save()} disabled={state === "saving"}>{state === "failed" ? "Retry save" : "Save"}</Button><Button onClick={() => void publish()} loading={state === "publishing"}>Publish</Button></div></div>
    <div className="grid gap-4 xl:grid-cols-[260px_minmax(0,1fr)_300px]"><Card><CardContent className="space-y-2 p-3"><p className="px-2 pt-1 text-xs font-medium uppercase tracking-wide text-muted-foreground">Sections</p>{sections.map((section, index) => <div key={section.id} draggable onDragStart={(event) => event.dataTransfer.setData("text/plain", section.id)} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); reorder(event.dataTransfer.getData("text/plain"), section.id); }} className={`flex items-center gap-1 rounded-lg p-1 ${section.id === selectedId ? "bg-surface-muted" : ""}`}><GripVertical className="h-4 w-4 cursor-grab text-muted-foreground" aria-label="Drag to reorder"/><button className="min-w-0 flex-1 truncate px-1 text-left text-sm" onClick={() => setSelectedId(section.id)}>{sectionLabel[section.type]}</button><Button size="sm" variant="ghost" className="h-7 w-7 p-0" onClick={() => update({ ...config, sections: sections.map((item) => item.id === section.id ? { ...item, visible: !item.visible } : item) })} aria-label={section.visible ? `Hide ${sectionLabel[section.type]}` : `Show ${sectionLabel[section.type]}`}>{section.visible ? <Eye className="h-4 w-4"/> : <EyeOff className="h-4 w-4"/>}</Button><Button size="sm" variant="ghost" className="h-7 w-7 p-0" onClick={() => move(section.id, -1)} disabled={index === 0} aria-label="Move section up">↑</Button><Button size="sm" variant="ghost" className="h-7 w-7 p-0" onClick={() => move(section.id, 1)} disabled={index === sections.length - 1} aria-label="Move section down">↓</Button><Button size="sm" variant="ghost" className="h-7 w-7 p-0 text-destructive" onClick={() => { update({ ...config, sections: normalize(sections.filter((item) => item.id !== section.id)) }); setSelectedId(null); }} aria-label={`Remove ${sectionLabel[section.type]}`}><Trash2 className="h-4 w-4"/></Button></div>)}<div className="border-t border-border pt-3"><p className="mb-2 px-2 text-xs font-medium text-muted-foreground">Add section</p><div className="grid grid-cols-2 gap-1">{PAGE_SECTION_TYPES.map((type) => <Button key={type} size="sm" variant="secondary" onClick={() => add(type)} disabled={singletonSections.includes(type) && sections.some((section) => section.type === type)}><Plus className="mr-1 h-3.5 w-3.5"/>{sectionLabel[type]}</Button>)}</div></div></CardContent></Card>
      <Card><CardContent className="min-h-[640px] bg-surface-muted p-5"><div className="mx-auto max-w-2xl space-y-4 rounded-xl bg-background p-6 shadow-sm"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Live draft preview</p>{sections.filter((section) => section.visible).map((section) => <PreviewSection key={section.id} section={section} />)}</div></CardContent></Card>
      <Card><CardContent className="space-y-4 p-5">{selected ? <><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Settings</p><h2 className="mt-1 font-semibold">{sectionLabel[selected.type]}</h2></div><div className="flex gap-1"><Button size="sm" variant="ghost" onClick={() => duplicate(selected)} disabled={singletonSections.includes(selected.type)} aria-label="Duplicate section"><Copy className="h-4 w-4"/></Button><Button size="sm" variant="ghost" onClick={resetSelected} aria-label="Reset section"><RotateCcw className="h-4 w-4"/></Button></div></div><SectionSettings section={selected} onChange={changeContent}/></> : <p className="text-sm text-muted-foreground">Select a section to edit its settings.</p>}</CardContent></Card></div></div>;
}

function SectionSettings({ section, onChange }: { section: PageSection; onChange: (key: string, value: string) => void }) {
  const text = (key: string) => String(section.content[key] ?? "");
  const updateItems = (key: string, items: Array<Record<string, string>>) => onChange(key, JSON.stringify(items));
  const parsedItems = (key: string, fallback: Array<Record<string, string>>) => { try { const value = section.content[key]; return typeof value === "string" ? JSON.parse(value) : Array.isArray(value) ? value : fallback; } catch { return fallback; } };
  if (section.type === "HERO") return <><Input label="Headline" value={text("headline")} onChange={(event) => onChange("headline", event.target.value)}/><Input label="Subheadline" value={text("subheadline")} onChange={(event) => onChange("subheadline", event.target.value)}/><Textarea label="Description" value={text("description")} onChange={(event) => onChange("description", event.target.value)}/></>;
  if (section.type === "SIGNUP") return <><Input label="Form title (optional)" value={text("title")} onChange={(event) => onChange("title", event.target.value)}/><Textarea label="Form subtitle (optional)" value={text("subtitle")} onChange={(event) => onChange("subtitle", event.target.value)}/></>;
  if (section.type === "FEATURES") { const items = parsedItems("items", [{ title: "", description: "" }]); return <><Input label="Section title" value={text("title")} onChange={(event) => onChange("title", event.target.value)}/><label className="block text-sm font-medium">Columns<select className="mt-1 w-full rounded-lg border border-input bg-background px-3 py-2" value={text("columns") || "3"} onChange={(event) => onChange("columns", event.target.value)}><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option></select></label>{items.map((item: Record<string, string>, index: number) => <div key={index} className="space-y-2 rounded-lg border border-border p-3"><Input label={`Feature ${index + 1} title`} value={item.title ?? ""} onChange={(event) => updateItems("items", items.map((value: Record<string, string>, i: number) => i === index ? { ...value, title: event.target.value } : value))}/><Textarea label="Feature description" value={item.description ?? ""} onChange={(event) => updateItems("items", items.map((value: Record<string, string>, i: number) => i === index ? { ...value, description: event.target.value } : value))}/></div>)}<Button size="sm" variant="secondary" disabled={items.length >= 6} onClick={() => updateItems("items", [...items, { title: "", description: "" }])}>Add feature</Button></>; }
  if (section.type === "FAQ") { const items = parsedItems("items", [{ question: "", answer: "" }]); return <><Input label="FAQ title" value={text("title")} onChange={(event) => onChange("title", event.target.value)}/>{items.map((item: Record<string, string>, index: number) => <div key={index} className="space-y-2 rounded-lg border border-border p-3"><Input label={`Question ${index + 1}`} value={item.question ?? ""} onChange={(event) => updateItems("items", items.map((value: Record<string, string>, i: number) => i === index ? { ...value, question: event.target.value } : value))}/><Textarea label="Answer" value={item.answer ?? ""} onChange={(event) => updateItems("items", items.map((value: Record<string, string>, i: number) => i === index ? { ...value, answer: event.target.value } : value))}/></div>)}<Button size="sm" variant="secondary" disabled={items.length >= 10} onClick={() => updateItems("items", [...items, { question: "", answer: "" }])}>Add FAQ</Button></>; }
  if (section.type === "SOCIAL_PROOF") return <><Input label="Section title" value={text("title")} onChange={(event) => onChange("title", event.target.value)}/><Textarea label="Description" value={text("description")} onChange={(event) => onChange("description", event.target.value)}/><div className="space-y-2"><label className="block text-sm font-medium" htmlFor="social-proof-screenshot">Screenshot</label><input id="social-proof-screenshot" className="block w-full text-sm" type="file" accept="image/*" onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; const uploaded = await uploadFile(file); onChange("screenshotUrl", uploaded.url); }}/>{text("screenshotUrl") && <img src={text("screenshotUrl")} alt="Social proof screenshot preview" className="max-h-40 rounded-lg border border-border object-cover"/>}</div></>;
  return <><Input label="Title" value={text("title")} onChange={(event) => onChange("title", event.target.value)}/><Textarea label={section.type === "FOOTER" ? "Footer text" : "Description"} value={text(section.type === "FOOTER" ? "text" : "description")} onChange={(event) => onChange(section.type === "FOOTER" ? "text" : "description", event.target.value)}/></>;
}

function PreviewSection({ section }: { section: PageSection }) { const title = String(section.content.headline ?? section.content.title ?? section.type.replace("_", " ")); const description = String(section.content.description ?? section.content.text ?? ""); return <section className="rounded-lg border border-border p-5"><p className="mb-2 text-xs font-medium text-muted-foreground">{sectionLabel[section.type]}</p><h2 className="text-xl font-semibold">{title}</h2>{description && <p className="mt-2 text-sm text-muted-foreground">{description}</p>}{section.type === "SIGNUP" && <div className="mt-4 h-10 rounded-lg bg-primary/15" />}{(section.type as string) === "COUNTDOWN" && <div className="mt-4 text-2xl font-semibold tabular-nums">00 : 00 : 00</div>}</section>; }
