FROM node:22-alpine

RUN apk add --no-cache \
    bash \
    openssl \
    ca-certificates \
    libc6-compat \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ttf-freefont

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

RUN npm i -g @nestjs/cli typescript ts-node prisma

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY prisma ./prisma
RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
